// Generated by tools/generate_donut_wrappers.py with donut.ts: don't edit, regenerate.
//
// For the editor (tsc, through tsconfig.json) only; tslang never reads it, as nothing references
// it. tslang makes donut.ts's classes global through the `/// <reference path="donut.ts" />` in
// input_pass.ts, exports and all; tsc treats donut.ts as a module because of the exports (which
// input_pass.dll needs, for the JIT), so this declares the classes as globals for it.

import * as Donut from "./donut";

declare global {
    type App = Donut.App;
    var App: typeof Donut.App;
    type Pass = Donut.Pass;
    var Pass: typeof Donut.Pass;
    type Frame = Donut.Frame;
    var Frame: typeof Donut.Frame;
    type CommandList = Donut.CommandList;
    var CommandList: typeof Donut.CommandList;
    type AdapterList = Donut.AdapterList;
    var AdapterList: typeof Donut.AdapterList;
    type InputLayoutDesc = Donut.InputLayoutDesc;
    var InputLayoutDesc: typeof Donut.InputLayoutDesc;
    type BindingSetDesc = Donut.BindingSetDesc;
    var BindingSetDesc: typeof Donut.BindingSetDesc;
    type BindingSet = Donut.BindingSet;
    var BindingSet: typeof Donut.BindingSet;
    type BindingLayoutDesc = Donut.BindingLayoutDesc;
    var BindingLayoutDesc: typeof Donut.BindingLayoutDesc;
    type BindlessLayoutDesc = Donut.BindlessLayoutDesc;
    var BindlessLayoutDesc: typeof Donut.BindlessLayoutDesc;
    type DescriptorTableManager = Donut.DescriptorTableManager;
    var DescriptorTableManager: typeof Donut.DescriptorTableManager;
    type RtPipelineDesc = Donut.RtPipelineDesc;
    var RtPipelineDesc: typeof Donut.RtPipelineDesc;
    type GraphicsPipelineDesc = Donut.GraphicsPipelineDesc;
    var GraphicsPipelineDesc: typeof Donut.GraphicsPipelineDesc;
    type ShaderTable = Donut.ShaderTable;
    var ShaderTable: typeof Donut.ShaderTable;
    type AsyncComputeLoop = Donut.AsyncComputeLoop;
    var AsyncComputeLoop: typeof Donut.AsyncComputeLoop;
    type ImGuiPass = Donut.ImGuiPass;
    var ImGuiPass: typeof Donut.ImGuiPass;
    type ImGuiFont = Donut.ImGuiFont;
    var ImGuiFont: typeof Donut.ImGuiFont;
    type SceneLoader = Donut.SceneLoader;
    var SceneLoader: typeof Donut.SceneLoader;
    type StringList = Donut.StringList;
    var StringList: typeof Donut.StringList;
    type Scene = Donut.Scene;
    var Scene: typeof Donut.Scene;
    type SceneGraph = Donut.SceneGraph;
    var SceneGraph: typeof Donut.SceneGraph;
    type Node = Donut.Node;
    var Node: typeof Donut.Node;
    type Light = Donut.Light;
    var Light: typeof Donut.Light;
    type Material = Donut.Material;
    var Material: typeof Donut.Material;
    type SceneCamera = Donut.SceneCamera;
    var SceneCamera: typeof Donut.SceneCamera;
    type SceneAccelStructs = Donut.SceneAccelStructs;
    var SceneAccelStructs: typeof Donut.SceneAccelStructs;
    type LoadedTexture = Donut.LoadedTexture;
    var LoadedTexture: typeof Donut.LoadedTexture;
    type Camera = Donut.Camera;
    var Camera: typeof Donut.Camera;
    type View = Donut.View;
    var View: typeof Donut.View;
    type CubemapTarget = Donut.CubemapTarget;
    var CubemapTarget: typeof Donut.CubemapTarget;
    type GBufferTargets = Donut.GBufferTargets;
    var GBufferTargets: typeof Donut.GBufferTargets;
    type TemporalTargets = Donut.TemporalTargets;
    var TemporalTargets: typeof Donut.TemporalTargets;
    type SceneRenderTargets = Donut.SceneRenderTargets;
    var SceneRenderTargets: typeof Donut.SceneRenderTargets;
    type ShadowMap = Donut.ShadowMap;
    var ShadowMap: typeof Donut.ShadowMap;
    type DepthPass = Donut.DepthPass;
    var DepthPass: typeof Donut.DepthPass;
    type ForwardShadingPass = Donut.ForwardShadingPass;
    var ForwardShadingPass: typeof Donut.ForwardShadingPass;
    type GBufferFillPass = Donut.GBufferFillPass;
    var GBufferFillPass: typeof Donut.GBufferFillPass;
    type DeferredLightingPass = Donut.DeferredLightingPass;
    var DeferredLightingPass: typeof Donut.DeferredLightingPass;
    type TemporalAntiAliasingPass = Donut.TemporalAntiAliasingPass;
    var TemporalAntiAliasingPass: typeof Donut.TemporalAntiAliasingPass;
    type ToneMappingPass = Donut.ToneMappingPass;
    var ToneMappingPass: typeof Donut.ToneMappingPass;
    type PixelReadbackPass = Donut.PixelReadbackPass;
    var PixelReadbackPass: typeof Donut.PixelReadbackPass;
    type Dlss = Donut.Dlss;
    var Dlss: typeof Donut.Dlss;
    type LightProbeSet = Donut.LightProbeSet;
    var LightProbeSet: typeof Donut.LightProbeSet;
    type LightProbeCapture = Donut.LightProbeCapture;
    var LightProbeCapture: typeof Donut.LightProbeCapture;
    type LightProbeProcessingPass = Donut.LightProbeProcessingPass;
    var LightProbeProcessingPass: typeof Donut.LightProbeProcessingPass;
}
